# Generated by Django 4.2.7 on 2023-12-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Enter stock keeping unit', max_length=100)),
                ('name', models.CharField(help_text='Enter product name', max_length=200)),
                ('description', models.TextField(help_text='Enter product description')),
                ('buyPrice', models.DecimalField(decimal_places=2, help_text='Enter product price per unit', max_digits=20)),
                ('sellPrice', models.DecimalField(decimal_places=2, help_text='Enter product price per unit', max_digits=20)),
                ('unit', models.CharField(help_text='ENTER TO PRODUCT', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=1, help_text='Enter quantity', max_digits=20)),
            ],
        ),
    ]
